### ISSUE TITLE
Help with Spodcast

### ISSUE THREAD

**Issue by hairy-tortoise** [heywoodlh/dockerfiles#3]
I can't get the Spodcast Web UI running. Can you maybe provide an docker-compose file for everything I need? Thank you!

**Comment by hairy-tortoise** [comment]
nvm I got it working

**Comment by heywoodlh** [comment]
Sorry, I just saw this. I have Spodcast running in my Kubernetes cluster using a Helm chart I wrote. If you understand Kubernetes at all it would be a useful resource: https://git.sr.ht/~heywoodlh/gitops/tree/master/item/charts/spodcast-web. Feel free to reach out if you have further questions: 

heywoodlh@tyrannyofthesun.com
