### ISSUE TITLE
gomuks docker image fails to launch

### ISSUE THREAD

**Issue by IFD3** [heywoodlh/dockerfiles#6]
Neither the Dockerfile nor the image on dockerhub runs at my machine.

```bash
docker run heywoodlh/gomuks
panic: failed to create screen: exec: "infocmp": executable file not found in $PATH [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xd1d618]

goroutine 1 [running]:
go.mau.fi/mauview.(*Application).ForceStop(...)
        /go/pkg/mod/go.mau.fi/mauview@v0.2.1/application.go:198
maunium.net/go/gomuks/ui.(*GomuksUI).Finish(0x40003dfca8?)
        /opt/gomuks/ui/ui.go:90 +0x28
maunium.net/go/gomuks/debug.Recover()
        /opt/gomuks/debug/debug.go:132 +0x44
panic({0xeb3a20, 0x400012c020})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
main.(*Gomuks).Start(0x40004ac360)
        /opt/gomuks/gomuks.go:175 +0x448
main.main()
        /opt/gomuks/main.go:119 +0x62c
```
infocmp is available on the host machine, which is a raspberry pi 4

**Comment by IFD3** [comment]
If I start the image with a TERM set, this happens:
```
docker run -e TERM=xterm  heywoodlh/gomuks
panic: failed to initialize screen: open /dev/tty: no such device or address [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xd1d618]

goroutine 1 [running]:
go.mau.fi/mauview.(*Application).ForceStop(...)
        /go/pkg/mod/go.mau.fi/mauview@v0.2.1/application.go:198
maunium.net/go/gomuks/ui.(*GomuksUI).Finish(0x40003bfca8?)
        /opt/gomuks/ui/ui.go:90 +0x28
maunium.net/go/gomuks/debug.Recover()
        /opt/gomuks/debug/debug.go:132 +0x44
panic({0xeb3a20, 0x4000550000})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
main.(*Gomuks).Start(0x400046e330)
        /opt/gomuks/gomuks.go:175 +0x448
main.main()
        /opt/gomuks/main.go:119 +0x62c
```

**Comment by heywoodlh** [comment]
I ran the following command and had no issues on MacOS and Linux (NixOS) on the latest image:

```
docker run -e TERM=xterm -it --rm heywoodlh/gomuks
```

Left side of this screenshot is running `docker` through Colima (so running Docker in an ARM64 Linux VM) locally on my M2 Macbook Air, right side is running Docker over SSH on my x86_64 Linux machine:

<img width="1459" alt="image" src="https://github.com/heywoodlh/dockerfiles/assets/18178614/5302a307-eb90-4628-aa66-dab5a1f32dad">


One potentially significant difference I can think of that my attempt to replicate this doesn't include: are you running the 32 bit version of Raspberry Pi OS? I.E. run `arch` on your Pi.

I haven't done any testing of this container on anything except 64 bit OS-es.

**Comment by heywoodlh** [comment]
Aha! It seems to be an issue specific to the `linux/arm/v7` variant of the image -- meaning that my suspicion of you running 32 bit Raspberry Pi OS is likely the difference.

<img width="826" alt="image" src="https://github.com/heywoodlh/dockerfiles/assets/18178614/0da93d16-c3ba-4f10-91b5-73ee3f076214">

**Comment by heywoodlh** [comment]
The most recent image build seems to have resolved this. Try re-pulling the latest image and trying again:

```
docker pull heywoodlh/gomuks
```

**Comment by IFD3** [comment]
First I was ahhh right, then I checked. I am running the default Debian aarch64. Well the lite image, because who needs a gui.
Pulling the latest image made no difference

**Comment by IFD3** [comment]
oh nevermind: docker run -e TERM=xterm -it --rm heywoodlh/gomuks works perfectly fine.
I wasn't aware that you have to start it interactively the first time.
without -it it crashes.
with -it it launches like it's probably should.

Since there was no instructions I thought I run the container, let it run forever and get interactive with the container whenever I want to use it.

**Comment by heywoodlh** [comment]
Awesome, glad you figured it out!

Will close this issue — feel free to re-open if desired.
